#crontab: "2 * * * *"

scm:
  url: https://git.tyil.nl/raku/Config/

sparrowdo:
  no_sudo: true
  no_index_update: false
  bootstrap: false
  format: default

disabled: false

allow_manual_run: true

keep_builds: 20
